name: Backend CI

on:
  push:
    branches:
      - main
      - feature/backend
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install coverage flake8

      - name: Run tests with coverage
        env:
          PYTHONPATH: backend/app:backend
        run: |
          coverage run --source=backend/app -m unittest discover tests/backend
          coverage report --fail-under=80
          coverage xml

      - name: Lint with flake8
        run: |
          flake8 backend/app

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
