name: Database CI

on:
  push:
    branches:
      - feature/db-init
      - feature/backend
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install coverage flake8

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/backend/app:${{ github.workspace }}/backend
        run: |
          python -m coverage run -m unittest discover -v -p "test_db_*.py" tests

      - name: Coverage report
        run: |
          python -m coverage report -m --fail-under=90

      - name: Lint with flake8
        run: |
          flake8 backend/app/db
